### ISSUE TITLE
Long (output) passwords will share entropy for adjacent counters

### ISSUE THREAD

**Issue by cipriancraciun** [samuel-lucas6/Cahir#2]
Based on the README, I make the assumption that the `counter` parameter is the actual `counter` value in the initial state as per <https://en.wikipedia.org/wiki/Salsa20#ChaCha_variant>
~~~~
ciphertext = ChaCha20(plaintext, nonce, key, counter)
~~~~

If so, given that the ChaCha20 block size is 512 bits, i.e. 64 bytes, and given that for each output letter 16 bytes are consumed, I gather that after 8 output characters the algorithm would move into the next block (i.e. next password "counter"), thus giving out "future" password characters.

~~~~
for i = 0 to length
    randomIndex = LE128(ciphertext.Slice(start: i * 16, length: 16)) % characterSet.Length
    sitePassword[i] = characterSet[randomIndex]
~~~~

This means that if an attacker recovers (say from a site dump) an old password, based on the password length, he already knows a few characters from the start of the next password.

----

Now, and this is something I've just realized now, because the `siteKey` already contains the `counter` as part of the hash input, the situation might be saved (because the ChaCha20 key is different, thus the counter is meaningless), but please check if this is the case.

----

Possible solution:
* as with the other issue (#1), perhaps the most elegant solution is to hash every input parameter as part of the Argon2id salt, and just leave the other parameters to ChaCha20 (like `nonce` and `counter` to plain 0;)

(BTW, the `nonce` input for ChaCha20 is not specified.)

**Comment by samuel-lucas6** [comment]
Thank you for having a look at this program. Yes, you're right about the ChaCha20 key changing every time.

The ChaCha20 counter is just the internal counter starting at 0. This is said in the specification, but the parameter does have the same name as the user-provided counter in the pseudocode.

Then the ChaCha20 nonce is set to a fixed value depending on whether a password or passphrase is being generated, which is also listed in the specification.

In other words, I'm basically doing what you said about leaving them to plain 0. However, instead of including all the user-provided parameters in the Argon2 salt, a lot of them are provided in the [site key derivation](https://github.com/samuel-lucas6/Cahir?tab=readme-ov-file#site-key-derivation) step. I can't remember the exact rationale for not using the salt, but it feels weird using the salt like an info parameter to me.

ChaCha20 is being used in place of an hash-based KDF/XOF because BLAKE2b doesn't have XOF functionality and there's no agreed way of doing key derivation (e.g., compared to HKDF or BLAKE3). It was also easier to just call ChaCha20 for that reason rather than implementing my own.
